# src/rhosocial/activerecord/backend/impl/mysql/expression/__init__.py
"""
MySQL-specific expression classes.

This module provides expression classes that are specific to MySQL, such as
LOAD DATA INFILE, JSON_TABLE, JSON functions, spatial functions, vector
functions, MATCH...AGAINST expressions, row-level locking expressions,
and JSON Duality View expressions.

Directory structure:
- load_data.py      - LOAD DATA INFILE expression
- json_table.py    - JSON_TABLE expression
- json.py           - JSON function expressions
- spatial.py         - Spatial function expressions
- vector.py          - Vector function expressions (MySQL 9.0+)
- match_against.py - MATCH...AGAINST expression
- locking.py        - Row-level locking expressions (FOR UPDATE, FOR SHARE)
- json_duality_view.py - JSON Duality View expressions (MySQL 9.7+)
- types.py          - MySQL-specific DataType subclasses for DDL
"""

from .table_options import MySQLCreateTableOptions
from .column import (
    MySQLColumnFormat,
    MySQLColumnStorage,
    MySQLColumnDefinition,
    MySQLColumnOptions,
)
from .load_data import MySQLLoadDataExpression, LoadDataOptions
from .json_table import MySQLJSONTableExpression, JSONTableColumn, NestedPath
from .json import (
    MySQLJSONExtractExpression,
    MySQLJSONObjectExpression,
    MySQLJSONArrayExpression,
    MySQLJSONContainsExpression,
    MySQLJSONUnquoteExpression,
    MySQLJSONSetExpression,
    MySQLJSONRemoveExpression,
    MySQLJSONTypeExpression,
    MySQLJSONValidExpression,
    MySQLJSONSearchExpression,
)
from .spatial import (
    MySQLSTGeomFromTextExpression,
    MySQLSTDistanceExpression,
    MySQLSTWithinExpression,
    MySQLSTContainsExpression,
    MySQLSpatialLiteralExpression,
    MySQLSTGeomFromWKBExpression,
    MySQLSTAsTextExpression,
    MySQLSTAsGeoJSONExpression,
    MySQLCreateSpatialIndexExpression,
)
from .vector import (
    MySQLVectorExpression,
    MySQLDistanceEuclideanExpression,
    MySQLDistanceCosineExpression,
    MySQLDistanceDotExpression,
    MySQLStringToVectorExpression,
    MySQLVectorToStringExpression,
    MySQLVectorDimExpression,
    MySQLCreateVectorIndexExpression,
)
from .set_type import (
    MySQLSetLiteralExpression,
    MySQLFindInSetExpression,
    MySQLSetContainsExpression,
)
from .fulltext import MySQLFulltextIndexOptionsExpression
from .table_expr import MySQLInlineIndexExpression, MySQLStorageOptionsExpression
from .match_against import MySQLMatchAgainstExpression, MatchAgainstMode
from .json_duality_view import (
    CreateJsonDualityViewExpression,
    DropJsonDualityViewExpression,
    DualityObjectSpec,
    DualityColumnMapping,
    DualityNestedMapping,
    DualityViewDMLTag,
    MySQLDualityObjectSelectExpression,
    MySQLDualityObjectBodyExpression,
    MySQLNestedDualityExpression,
)
from .optimizer_hint import (
    MySQLOptimizerHintExpression,
    SetVarHint,
    OptimizerHintType,
)
from .partition import (
    MySQLPartitionStrategy,
    MySQLPartitionClause,
    MySQLPartitionMaxValue,
    MySQLPartitionValue,
    MySQLPartitionDefinition,
    MySQLPartitionByRange,
    MySQLPartitionByRangeColumns,
    MySQLPartitionByList,
    MySQLPartitionByListColumns,
    MySQLPartitionByHash,
    MySQLPartitionByKey,
    MySQLAddPartitionExpression,
    MySQLDropPartitionExpression,
    MySQLTruncatePartitionExpression,
    MySQLReorganizePartitionExpression,
    MySQLExchangePartitionExpression,
    MySQLRemovePartitioningExpression,
    MySQLCoalescePartitionExpression,
    MySQLAnalyzePartitionExpression,
    MySQLCheckPartitionExpression,
    MySQLOptimizePartitionExpression,
    MySQLRebuildPartitionExpression,
    MySQLRepairPartitionExpression,
    MySQLGetPartitionsExpression,
    MySQLSubpartitionStrategy,
    MySQLSubpartitionDefinition,
    MySQLSubpartitionClause,
)
from .partition_lifecycle import (
    MySQLAddPartitionHelper,
    MySQLAddSubpartitionHelper,
    MySQLCoalescePartitionHelper,
    MySQLDropOldestPartitionHelper,
    MySQLReorganizePartitionHelper,
)
from .rename_table import MySQLRenameTableExpression
from .table_statement import MySQLTableExpression, MySQLValuesExpression
from .maintenance import (
    MySQLAnalyzeTableExpression,
    MySQLCheckTableExpression,
    MySQLChecksumTableExpression,
    MySQLOptimizeTableExpression,
    MySQLRepairTableExpression,
    CheckTableOption,
    ChecksumTableOption,
    RepairTableOption,
    NoWriteToBinlogOption,
)
from .routine import (
    MySQLCallExpression,
    MySQLCreateProcedureExpression,
    MySQLDropProcedureExpression,
    MySQLCreateFunctionExpression,
    MySQLDropFunctionExpression,
)
from .load_xml import MySQLLoadXMLEXpression, LoadXMLPriority, LoadXMLConflictMode
from .admin import (
    MySQLCacheIndexExpression,
    MySQLLoadIndexIntoCacheExpression,
    MySQLFlushExpression,
    FlushOption,
    MySQLResetExpression,
    ResetOption,
    MySQLInstallComponentExpression,
    MySQLUninstallComponentExpression,
    MySQLInstallPluginExpression,
    MySQLUninstallPluginExpression,
    MySQLCloneExpression,
    MySQLRestartExpression,
    MySQLBinlogExpression,
    MySQLHandlerOpenExpression,
    MySQLHandlerReadExpression,
    MySQLHandlerCloseExpression,
    HandlerReadMode,
    MySQLDoExpression,
    MySQLKillExpression,
    KillTarget,
    MySQLShutdownExpression,
    MySQLHelpExpression,
    AccountSpec,
    GrantPrivilege,
    MySQLCreateUserExpression,
    MySQLDropUserExpression,
    MySQLGrantExpression,
    MySQLRevokeExpression,
)

# DataType subclasses for DDL
from .types import (
    MySQLBigIntType,
    MySQLBinaryType,
    MySQLBitType,
    MySQLBlobType,
    MySQLEnumType,
    MySQLGeometryCollectionType,
    MySQLGeometryType,
    MySQLIntType,
    MySQLLineStringType,
    MySQLLongBlobType,
    MySQLLongTextType,
    MySQLMediumBlobType,
    MySQLMediumTextType,
    MySQLMultiLineStringType,
    MySQLMultiPointType,
    MySQLMultiPolygonType,
    MySQLPointType,
    MySQLPolygonType,
    MySQLSetType,
    MySQLSmallIntType,
    MySQLTextType,
    MySQLTinyBlobType,
    MySQLTinyIntType,
    MySQLTinyTextType,
    MySQLVarBinaryType,
    MySQLVectorType,
    MySQLYearType,
)

__all__ = [
    "MySQLLoadDataExpression",
    "LoadDataOptions",
    "MySQLCreateTableOptions",
    "MySQLColumnFormat",
    "MySQLColumnStorage",
    "MySQLColumnDefinition",
    "MySQLColumnOptions",
    "MySQLJSONTableExpression",
    "JSONTableColumn",
    "NestedPath",
    "MySQLJSONExtractExpression",
    "MySQLJSONObjectExpression",
    "MySQLJSONArrayExpression",
    "MySQLJSONContainsExpression",
    "MySQLJSONUnquoteExpression",
    "MySQLJSONSetExpression",
    "MySQLJSONRemoveExpression",
    "MySQLJSONTypeExpression",
    "MySQLJSONValidExpression",
    "MySQLJSONSearchExpression",
    "MySQLSTGeomFromTextExpression",
    "MySQLSTDistanceExpression",
    "MySQLSTWithinExpression",
    "MySQLSTContainsExpression",
    "MySQLSpatialLiteralExpression",
    "MySQLSTGeomFromWKBExpression",
    "MySQLSTAsTextExpression",
    "MySQLSTAsGeoJSONExpression",
    "MySQLCreateSpatialIndexExpression",
    "MySQLVectorExpression",
    "MySQLDistanceEuclideanExpression",
    "MySQLDistanceCosineExpression",
    "MySQLDistanceDotExpression",
    "MySQLStringToVectorExpression",
    "MySQLVectorToStringExpression",
    "MySQLVectorDimExpression",
    "MySQLCreateVectorIndexExpression",
    "MySQLSetLiteralExpression",
    "MySQLFindInSetExpression",
    "MySQLSetContainsExpression",
    "MySQLFulltextIndexOptionsExpression",
    "MySQLInlineIndexExpression",
    "MySQLStorageOptionsExpression",
    "MySQLMatchAgainstExpression",
    "MatchAgainstMode",
    "CreateJsonDualityViewExpression",
    "DropJsonDualityViewExpression",
    "DualityObjectSpec",
    "DualityColumnMapping",
    "DualityNestedMapping",
    "DualityViewDMLTag",
    "MySQLDualityObjectSelectExpression",
    "MySQLDualityObjectBodyExpression",
    "MySQLNestedDualityExpression",
    "MySQLOptimizerHintExpression",
    "SetVarHint",
    "OptimizerHintType",
    "MySQLPartitionStrategy",
    "MySQLPartitionClause",
    "MySQLPartitionMaxValue",
    "MySQLPartitionValue",
    "MySQLPartitionDefinition",
    "MySQLPartitionByRange",
    "MySQLPartitionByRangeColumns",
    "MySQLPartitionByList",
    "MySQLPartitionByListColumns",
    "MySQLPartitionByHash",
    "MySQLPartitionByKey",
    "MySQLAddPartitionExpression",
    "MySQLDropPartitionExpression",
    "MySQLTruncatePartitionExpression",
    "MySQLReorganizePartitionExpression",
    "MySQLExchangePartitionExpression",
    "MySQLRemovePartitioningExpression",
    "MySQLCoalescePartitionExpression",
    "MySQLAnalyzePartitionExpression",
    "MySQLCheckPartitionExpression",
    "MySQLOptimizePartitionExpression",
    "MySQLRebuildPartitionExpression",
    "MySQLRepairPartitionExpression",
    "MySQLSubpartitionStrategy",
    "MySQLSubpartitionDefinition",
    "MySQLSubpartitionClause",
    "MySQLRenameTableExpression",
    "MySQLTableExpression",
    "MySQLValuesExpression",
    "MySQLAnalyzeTableExpression",
    "MySQLCheckTableExpression",
    "MySQLChecksumTableExpression",
    "MySQLOptimizeTableExpression",
    "MySQLRepairTableExpression",
    "CheckTableOption",
    "ChecksumTableOption",
    "RepairTableOption",
    "NoWriteToBinlogOption",
    "MySQLCallExpression",
    "MySQLCreateProcedureExpression",
    "MySQLDropProcedureExpression",
    "MySQLCreateFunctionExpression",
    "MySQLDropFunctionExpression",
    "MySQLLoadXMLEXpression",
    "LoadXMLPriority",
    "LoadXMLConflictMode",
    "MySQLCacheIndexExpression",
    "MySQLLoadIndexIntoCacheExpression",
    "MySQLFlushExpression",
    "FlushOption",
    "MySQLResetExpression",
    "ResetOption",
    "MySQLInstallComponentExpression",
    "MySQLUninstallComponentExpression",
    "MySQLInstallPluginExpression",
    "MySQLUninstallPluginExpression",
    "MySQLCloneExpression",
    "MySQLRestartExpression",
    "MySQLBinlogExpression",
    "MySQLHandlerOpenExpression",
    "MySQLHandlerReadExpression",
    "MySQLHandlerCloseExpression",
    "HandlerReadMode",
    "MySQLDoExpression",
    "MySQLKillExpression",
    "KillTarget",
    "MySQLShutdownExpression",
    "MySQLHelpExpression",
    "AccountSpec",
    "GrantPrivilege",
    "MySQLCreateUserExpression",
    "MySQLDropUserExpression",
    "MySQLGrantExpression",
    "MySQLRevokeExpression",
    # DataType subclasses for DDL
    "MySQLBigIntType",
    "MySQLBinaryType",
    "MySQLBitType",
    "MySQLBlobType",
    "MySQLEnumType",
    "MySQLGeometryCollectionType",
    "MySQLGeometryType",
    "MySQLIntType",
    "MySQLLineStringType",
    "MySQLLongBlobType",
    "MySQLLongTextType",
    "MySQLMediumBlobType",
    "MySQLMediumTextType",
    "MySQLMultiLineStringType",
    "MySQLMultiPointType",
    "MySQLMultiPolygonType",
    "MySQLPointType",
    "MySQLPolygonType",
    "MySQLSetType",
    "MySQLSmallIntType",
    "MySQLTextType",
    "MySQLTinyBlobType",
    "MySQLTinyIntType",
    "MySQLTinyTextType",
    "MySQLVarBinaryType",
    "MySQLVectorType",
    "MySQLYearType",
]
