# tests/rhosocial/activerecord_mysql_test/feature/backend/functions/test_json_functions_factory.py
"""
Tests for the MySQL JSON function factories.

These are pure expression-level (no live server needed) tests that pin the SQL
generated by ``src/rhosocial/activerecord/backend/impl/mysql/functions/json.py``:

- ``_convert_to_expression`` literal/column conversion rules
- ``json_extract``/``json_unquote``/``json_object``/``json_array``
- ``json_contains``/``json_set``/``json_remove``/``json_type``/``json_valid``
- ``json_search`` one/all mode with and without a path
"""

import pytest

from rhosocial.activerecord.backend.expression import Column
from rhosocial.activerecord.backend.expression.core import FunctionCall, Literal
from rhosocial.activerecord.backend.impl.mysql.dialect import MySQLDialect
from rhosocial.activerecord.backend.impl.mysql.functions.json import (
    _convert_to_expression,
    json_array,
    json_contains,
    json_extract,
    json_object,
    json_remove,
    json_search,
    json_set,
    json_type,
    json_unquote,
    json_valid,
)


@pytest.fixture
def dialect():
    """Return a MySQLDialect instance for function formatting."""
    return MySQLDialect(version=(8, 0, 0))


class TestConvertToExpression:
    """Verify _convert_to_expression literal/column conversion rules."""

    def test_base_expression_passthrough(self, dialect):
        """A BaseExpression should be returned unchanged."""
        column = Column(dialect, "data")
        result = _convert_to_expression(dialect, column)
        assert result is column, "existing expression should pass through unchanged"

    def test_string_becomes_column(self, dialect):
        """A plain string should be converted to a Column."""
        result = _convert_to_expression(dialect, "data")
        assert isinstance(result, Column), "string input should become a Column"

    def test_numeric_becomes_literal(self, dialect):
        """An integer should become a Literal when numeric literals are handled."""
        result = _convert_to_expression(dialect, 42)
        assert isinstance(result, Literal), "integer input should become a Literal"

    def test_float_becomes_literal(self, dialect):
        """A float should become a Literal when numeric literals are handled."""
        result = _convert_to_expression(dialect, 3.14)
        assert isinstance(result, Literal), "float input should become a Literal"

    def test_numeric_handling_disabled(self, dialect):
        """A numeric input should become a Column when numeric literals are disabled."""
        result = _convert_to_expression(dialect, 42, handle_numeric_literals=False)
        assert isinstance(result, Column), "numeric input should become a Column when disabled"


class TestJsonExtract:
    """Verify json_extract builds JSON_EXTRACT function calls."""

    def test_single_path(self, dialect):
        """A single path should be bound as a parameter."""
        call = json_extract(dialect, Column(dialect, "data"), "$.name")
        assert isinstance(call, FunctionCall), "json_extract should return a FunctionCall"
        sql, params = call.to_sql()
        assert sql == "JSON_EXTRACT(`data`, %s)", f"unexpected SQL: {sql}"
        assert params == ("$.name",), "path should be bound as parameter"

    def test_multiple_paths(self, dialect):
        """Multiple paths should each be bound as parameters."""
        call = json_extract(dialect, Column(dialect, "data"), "$.name", "$.age", "$.city")
        sql, params = call.to_sql()
        assert sql == "JSON_EXTRACT(`data`, %s, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("$.name", "$.age", "$.city"), "all paths should be bound"

    def test_literal_document(self, dialect):
        """A literal JSON document should be rendered as a bound parameter."""
        call = json_extract(dialect, 5, "$.a")
        sql, params = call.to_sql()
        assert sql == "JSON_EXTRACT(%s, %s)", f"unexpected SQL: {sql}"
        assert params == (5, "$.a"), "numeric document should be a bound literal"


class TestJsonUnquote:
    """Verify json_unquote builds JSON_UNQUOTE function calls."""

    def test_column(self, dialect):
        """A column should be wrapped by JSON_UNQUOTE."""
        call = json_unquote(dialect, Column(dialect, "data"))
        sql, params = call.to_sql()
        assert sql == "JSON_UNQUOTE(`data`)", f"unexpected SQL: {sql}"
        assert params == (), "JSON_UNQUOTE on a column has no parameters"

    def test_string(self, dialect):
        """A string value should be rendered as a quoted column reference."""
        call = json_unquote(dialect, '"John"')
        sql, params = call.to_sql()
        assert sql == 'JSON_UNQUOTE(`"John"`)', f"unexpected SQL: {sql}"
        assert params == (), "string literal path has no parameters"


class TestJsonObject:
    """Verify json_object builds JSON_OBJECT function calls."""

    def test_empty(self, dialect):
        """An empty JSON_OBJECT should render without arguments."""
        call = json_object(dialect)
        sql, params = call.to_sql()
        assert sql == "JSON_OBJECT()", f"unexpected SQL: {sql}"
        assert params == (), "empty JSON_OBJECT has no parameters"

    def test_single_pair(self, dialect):
        """A single key-value pair should be bound as two parameters."""
        call = json_object(dialect, "name", "John")
        sql, params = call.to_sql()
        assert sql == "JSON_OBJECT(%s, %s)", f"unexpected SQL: {sql}"
        assert params == ("name", "John"), "key and value should be bound"

    def test_multiple_pairs(self, dialect):
        """Multiple key-value pairs should all be bound as parameters."""
        call = json_object(dialect, "name", "John", "age", 30)
        sql, params = call.to_sql()
        assert sql == "JSON_OBJECT(%s, %s, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("name", "John", "age", 30), "all pairs should be bound"


class TestJsonArray:
    """Verify json_array builds JSON_ARRAY function calls."""

    def test_empty(self, dialect):
        """An empty JSON_ARRAY should render without arguments."""
        call = json_array(dialect)
        sql, params = call.to_sql()
        assert sql == "JSON_ARRAY()", f"unexpected SQL: {sql}"
        assert params == (), "empty JSON_ARRAY has no parameters"

    def test_values(self, dialect):
        """Values should be bound as parameters."""
        call = json_array(dialect, 1, "a", True, None)
        sql, params = call.to_sql()
        assert sql == "JSON_ARRAY(%s, %s, %s, %s)", f"unexpected SQL: {sql}"
        assert params == (1, "a", True, None), "all values should be bound"


class TestJsonContains:
    """Verify json_contains builds JSON_CONTAINS function calls."""

    def test_no_path(self, dialect):
        """Without a path only target and candidate should be emitted."""
        call = json_contains(dialect, Column(dialect, "data"), '"John"')
        sql, params = call.to_sql()
        assert sql == "JSON_CONTAINS(`data`, %s)", f"unexpected SQL: {sql}"
        assert params == ('"John"',), "candidate should be bound"

    def test_with_path(self, dialect):
        """With a path the third argument should be bound."""
        call = json_contains(dialect, Column(dialect, "data"), "2", "$.age")
        sql, params = call.to_sql()
        assert sql == "JSON_CONTAINS(`data`, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("2", "$.age"), "candidate and path should be bound"


class TestJsonSet:
    """Verify json_set builds JSON_SET function calls."""

    def test_single_pair(self, dialect):
        """A single path-value pair should be bound."""
        call = json_set(dialect, Column(dialect, "data"), "$.name", "John")
        sql, params = call.to_sql()
        assert sql == "JSON_SET(`data`, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("$.name", "John"), "path and value should be bound"

    def test_multiple_pairs(self, dialect):
        """Additional path-value pairs should be bound in order."""
        call = json_set(dialect, Column(dialect, "data"), "$.name", "John", "$.age", 30, "$.city", "NYC")
        sql, params = call.to_sql()
        assert sql == "JSON_SET(`data`, %s, %s, %s, %s, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("$.name", "John", "$.age", 30, "$.city", "NYC"), "pairs should be bound in order"


class TestJsonRemove:
    """Verify json_remove builds JSON_REMOVE function calls."""

    def test_single_path(self, dialect):
        """A single path should be bound."""
        call = json_remove(dialect, Column(dialect, "data"), "$.temp")
        sql, params = call.to_sql()
        assert sql == "JSON_REMOVE(`data`, %s)", f"unexpected SQL: {sql}"
        assert params == ("$.temp",), "path should be bound"

    def test_multiple_paths(self, dialect):
        """Multiple paths should each be bound."""
        call = json_remove(dialect, Column(dialect, "data"), "$.temp", "$.cache")
        sql, params = call.to_sql()
        assert sql == "JSON_REMOVE(`data`, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("$.temp", "$.cache"), "all paths should be bound"


class TestJsonTypeAndValid:
    """Verify json_type and json_valid build simple wrapper calls."""

    def test_json_type(self, dialect):
        """JSON_TYPE should wrap the target expression."""
        call = json_type(dialect, Column(dialect, "data"))
        sql, params = call.to_sql()
        assert sql == "JSON_TYPE(`data`)", f"unexpected SQL: {sql}"
        assert params == (), "JSON_TYPE on a column has no parameters"

    def test_json_valid(self, dialect):
        """JSON_VALID should wrap the target expression."""
        call = json_valid(dialect, Column(dialect, "data"))
        sql, params = call.to_sql()
        assert sql == "JSON_VALID(`data`)", f"unexpected SQL: {sql}"
        assert params == (), "JSON_VALID on a column has no parameters"


class TestJsonSearch:
    """Verify json_search builds JSON_SEARCH calls for one/all mode and paths."""

    def test_one_mode(self, dialect):
        """One mode should emit 'one' as the second argument."""
        call = json_search(dialect, Column(dialect, "data"), "John")
        sql, params = call.to_sql()
        assert sql == "JSON_SEARCH(`data`, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("one", "John"), "mode and search string should be bound"

    def test_all_mode(self, dialect):
        """All mode should emit 'all' as the second argument."""
        call = json_search(dialect, Column(dialect, "data"), "John", search_all=True)
        sql, params = call.to_sql()
        assert sql == "JSON_SEARCH(`data`, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("all", "John"), "mode and search string should be bound"

    def test_with_path(self, dialect):
        """With a path, a NULL escape and the path should be appended."""
        call = json_search(dialect, Column(dialect, "data"), "John", path="$.users", search_all=True)
        sql, params = call.to_sql()
        assert sql == "JSON_SEARCH(`data`, %s, %s, %s, %s)", f"unexpected SQL: {sql}"
        assert params == ("all", "John", None, "$.users"), "escape and path should be bound"


class TestJsonFactoriesExports:
    """Verify the factory module exposes the documented function surface."""

    def test_all_exports(self):
        """All documented JSON factories should be present in __all__."""
        import rhosocial.activerecord.backend.impl.mysql.functions.json as json_module

        expected = {
            "json_extract",
            "json_unquote",
            "json_object",
            "json_array",
            "json_contains",
            "json_set",
            "json_remove",
            "json_type",
            "json_valid",
            "json_search",
        }
        assert set(json_module.__all__) == expected, "module __all__ should match the documented factories"