name: Python Package Publish

on:
  # 当测试工作流成功完成时自动触发发布审批流程
  workflow_run:
    workflows: ["Python Test and Coverage"]
    types:
      - completed
    branches:
      - main

  # 手动触发发布工作流
  workflow_dispatch:
    inputs:
      destination:
        description: '发布目标'
        required: true
        default: 'testpypi'
        type: choice
        options:
          - testpypi
          - pypi

jobs:
  # 检查测试工作流是否成功完成
  check-tests:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'workflow_dispatch'
    steps:
      - name: Success check
        run: echo "前置测试通过，可以继续执行发布流程"

  # 发布到TestPyPI
  publish-testpypi:
    name: Publish to TestPyPI
    needs: check-tests
    if: >
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.destination == 'testpypi')
    runs-on: ubuntu-latest
    environment: publish-testpypi  # 使用需要审批的环境
    permissions:
      # Required for trusted publishing
      id-token: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true
        # Note: removed user and password fields to use Trusted Publishers

  # 发布到PyPI
  publish-pypi:
    name: Publish to PyPI
    needs: check-tests
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.destination == 'pypi'
    runs-on: ubuntu-latest
    environment: publish-pypi  # 使用需要严格审批的环境
    permissions:
      # Required for trusted publishing
      id-token: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # Note: removed user and password fields to use Trusted Publishers